[package]
name = "trustballot"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk = { git = "https://github.com/linera-io/linera-protocol", branch = "main" }
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
